core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import MainPageView, EkbMapView, TulaMapView

app_name = 'main'


urlpatterns = [
    path('', MainPageView.as_view(), name='main_page'),
    path('ekb/', EkbMapView.as_view(), name='ekb'),
    path('tula/', TulaMapView.as_view(), name='tula'),
]

main/views.py
from django.shortcuts import render, redirect
from django.views import View


class MainPageView(View):
    def get(self, request):
        return render(request, 'index.html')
    

class EkbMapView(View):
    def get(self, request):
        return render(request, 'ekb.html')
    

class TulaMapView(View):
    def get(self, request):
        return render(request, 'tula.html')

templates/index.html
{% load static %}
{% csrf_token %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>AIProsto</title>
</head>
<body>
    <div>
        <div>
            <p data-item='AI-PROSTO'>AI-PROSTO</p>

            <section>
            <div>Выберите город, чтобы посмотреть данные</div>
            <nav>
                <ul class="menuItems">
                <li><a href="{% url 'main:ekb' %}" data-item='Екатеринбург'>Екатеринбург</a></li>
                <li><a href="{% url 'main:tula' %}" data-item='Тула'>Тула</a></li>
                </ul>
            </nav>
            </section>
        </div>
    </div>
</body>
</html>